#!/usr/bin/env bash
# ── Hub — Azure One-Step Quickstart ───────────────────────────────
# Generates all secrets, deploys to Azure Container Instance, and
# prints the URL and credentials when done.
#
# Usage (from the webui-hub directory):
#   bash deploy-azure-quickstart.sh
#
# Optional overrides (set before running):
#   export ADMIN_PASSWORD=MySecurePass123
#   export RG=my-resource-group
#   export LOCATION=eastus

set -euo pipefail

SECRETS_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.deploy-secrets.env"

# ── Prerequisite check ────────────────────────────────────────────
if ! command -v az &>/dev/null; then
    echo "❌ Azure CLI not found. Install from https://aka.ms/installazurecli"
    exit 1
fi
if ! command -v python3 &>/dev/null; then
    echo "❌ python3 not found."
    exit 1
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Hub — Azure Quickstart Deploy"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ── Load saved secrets if they exist ─────────────────────────────
if [ -f "$SECRETS_FILE" ]; then
    echo "  ♻  Loading saved secrets from .deploy-secrets.env"
    # shellcheck source=/dev/null
    source "$SECRETS_FILE"
fi

# ── Generate secrets if not already set ───────────────────────────
if [ -z "${WEBUI_SECRET_KEY:-}" ]; then
    WEBUI_SECRET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null \
        || python3 -c "import base64, os; print(base64.urlsafe_b64encode(os.urandom(32)).decode())")
    echo "  ✔ Generated WEBUI_SECRET_KEY"
fi

if [ -z "${SECRET_KEY:-}" ]; then
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(48))")
    echo "  ✔ Generated SECRET_KEY"
fi

if [ -z "${ADMIN_PASSWORD:-}" ]; then
    ADMIN_PASSWORD="TeamFirst!"
    echo "  ✔ ADMIN_PASSWORD set to: $ADMIN_PASSWORD"
fi

if [ -z "${ENCRYPTION_KEY:-}" ]; then
    ENCRYPTION_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
    echo "  ✔ Generated ENCRYPTION_KEY"
fi

if [ -z "${INSTALLER_API_KEY:-}" ]; then
    INSTALLER_API_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))")
    echo "  ✔ Generated INSTALLER_API_KEY"
fi

export WEBUI_SECRET_KEY SECRET_KEY ADMIN_PASSWORD ENCRYPTION_KEY INSTALLER_API_KEY

# ── Save secrets for future runs ──────────────────────────────────
cat > "$SECRETS_FILE" <<EOF
# Hub deploy secrets — generated by deploy-azure-quickstart.sh
# ⚠  Keep this file private — it is gitignored and never committed.
WEBUI_SECRET_KEY=$WEBUI_SECRET_KEY
SECRET_KEY=$SECRET_KEY
ADMIN_PASSWORD=$ADMIN_PASSWORD
ENCRYPTION_KEY=$ENCRYPTION_KEY
INSTALLER_API_KEY=$INSTALLER_API_KEY
EOF
chmod 600 "$SECRETS_FILE"
echo "  💾 Secrets saved to .deploy-secrets.env (gitignored)"
echo ""

# ── Run main deploy script ────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
bash "$SCRIPT_DIR/deploy-azure.sh"

echo ""
echo "  Secrets saved to  : .deploy-secrets.env (gitignored — reused on next deploy)"
echo "  ADMIN_PASSWORD   : $ADMIN_PASSWORD"
echo "  WEBUI_SECRET_KEY : [set]"
echo "  SECRET_KEY       : [set]"
echo "  ENCRYPTION_KEY   : [set]"
echo "  INSTALLER_API_KEY: [set]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
