#!/usr/bin/env bash
# ── Hub — BYOD Linux Installer ────────────────────────────────────
# Installs Hub on any Linux system (Ubuntu/Debian/RHEL/Rocky/Alma).
# Creates a systemd service running as a dedicated user.
#
# Usage (as root or with sudo):
#   curl -fsSL https://raw.githubusercontent.com/solutions-hpe/webui-hub/main/install.sh | bash
#   OR
#   bash install.sh
#
# Optional env vars:
#   INSTALL_DIR   (default: /opt/hub)
#   DATA_DIR      (default: /var/lib/hub)
#   HUB_PORT      (default: 8443)
#   ADMIN_PASSWORD
#   WEBUI_SECRET_KEY
#   SECRET_KEY

set -euo pipefail

INSTALL_DIR="${INSTALL_DIR:-/opt/hub}"
DATA_DIR="${DATA_DIR:-/var/lib/hub}"
HUB_USER="hub"
HUB_PORT="${HUB_PORT:-8443}"
SERVICE_NAME="hub"
PYTHON="${PYTHON:-python3}"
REPO_URL="https://github.com/solutions-hpe/webui-hub"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "${GREEN}▶${NC} $*"; }
warn()    { echo -e "${YELLOW}⚠${NC} $*"; }
error()   { echo -e "${RED}❌${NC} $*" >&2; exit 1; }

# ── Root check ────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
    error "Please run as root or with sudo"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Hub — BYOD Linux Installer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Install dir : $INSTALL_DIR"
echo "  Data dir    : $DATA_DIR"
echo "  Port        : $HUB_PORT"
echo "  Service     : $SERVICE_NAME"
echo ""

# ── Python check ─────────────────────────────────────────────────
info "Checking Python..."
if ! command -v "$PYTHON" &>/dev/null; then
    error "Python 3 not found. Install python3 first."
fi
PY_VERSION=$($PYTHON -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
info "Found Python $PY_VERSION"
if $PYTHON -c "import sys; sys.exit(0 if sys.version_info >= (3,9) else 1)"; then
    info "Python version OK"
else
    error "Python 3.9+ required (found $PY_VERSION)"
fi

# ── System user ───────────────────────────────────────────────────
info "Creating system user '$HUB_USER'..."
if ! id "$HUB_USER" &>/dev/null; then
    useradd --system --shell /usr/sbin/nologin --home-dir "$INSTALL_DIR" --create-home "$HUB_USER"
fi

# ── Install directory ─────────────────────────────────────────────
info "Setting up install directory..."
mkdir -p "$INSTALL_DIR"
if [ -d "$INSTALL_DIR/.git" ]; then
    info "Existing install found — pulling latest..."
    cd "$INSTALL_DIR"
    git pull
else
    info "Cloning repository..."
    git clone "$REPO_URL" "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi

# ── Data directory ────────────────────────────────────────────────
info "Setting up data directory..."
mkdir -p "$DATA_DIR"/{tls,pending}
chown -R "$HUB_USER:$HUB_USER" "$DATA_DIR"

# ── Python virtual environment ────────────────────────────────────
info "Creating Python virtual environment..."
if [ ! -d "$INSTALL_DIR/venv" ]; then
    $PYTHON -m venv "$INSTALL_DIR/venv"
fi
"$INSTALL_DIR/venv/bin/pip" install --quiet --upgrade pip
"$INSTALL_DIR/venv/bin/pip" install --quiet -r "$INSTALL_DIR/requirements.txt"
info "Dependencies installed."

# ── Generate secrets if not provided ─────────────────────────────
if [ -z "${WEBUI_SECRET_KEY:-}" ]; then
    warn "WEBUI_SECRET_KEY not set — generating one now."
    WEBUI_SECRET_KEY=$("$INSTALL_DIR/venv/bin/python3" -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
    warn "WEBUI_SECRET_KEY=$WEBUI_SECRET_KEY"
    warn "Save this key! Losing it makes encrypted secrets unrecoverable."
fi
if [ -z "${SECRET_KEY:-}" ]; then
    SECRET_KEY=$("$INSTALL_DIR/venv/bin/python3" -c "import secrets; print(secrets.token_urlsafe(48))")
fi
ADMIN_PASSWORD="${ADMIN_PASSWORD:-changeme}"
if [ "$ADMIN_PASSWORD" = "changeme" ]; then
    warn "Using default ADMIN_PASSWORD='changeme' — change this after first login!"
fi

# ── Generate TLS certificate ──────────────────────────────────────
info "Generating TLS certificate..."
"$INSTALL_DIR/venv/bin/python3" -c "
from pathlib import Path
from app.tls import generate_self_signed
cert = Path('$DATA_DIR/tls/cert.pem')
key = Path('$DATA_DIR/tls/key.pem')
if not cert.exists() or not key.exists():
    cert.parent.mkdir(parents=True, exist_ok=True)
    generate_self_signed(cert, key)
    print('TLS certificate generated.')
else:
    print('TLS certificate already exists, skipping.')
" 2>/dev/null || warn "TLS cert generation skipped — start.sh will generate it on first start."

# ── Environment file ──────────────────────────────────────────────
info "Writing environment file..."
ENV_FILE="$INSTALL_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Hub Environment — generated by install.sh
WEBUI_SECRET_KEY=$WEBUI_SECRET_KEY
SECRET_KEY=$SECRET_KEY
ADMIN_PASSWORD=$ADMIN_PASSWORD
DATA_DIR=$DATA_DIR
HUB_PORT=$HUB_PORT
TLS_CERT_PATH=$DATA_DIR/tls/cert.pem
TLS_KEY_PATH=$DATA_DIR/tls/key.pem
PYTHON_BIN=$INSTALL_DIR/venv/bin/python3
EOF
chmod 600 "$ENV_FILE"
chown "$HUB_USER:$HUB_USER" "$ENV_FILE"

# ── Firewall ─────────────────────────────────────────────────────
info "Configuring firewall..."
if command -v ufw &>/dev/null; then
    ufw --force enable
    ufw default deny incoming
    ufw default allow outgoing
    ufw allow ssh
    ufw allow "$HUB_PORT"/tcp comment "Hub HTTPS"
    ufw --force reload
    info "ufw: enabled — only SSH and port $HUB_PORT allowed inbound."
elif command -v firewall-cmd &>/dev/null; then
    systemctl enable --now firewalld
    firewall-cmd --permanent --set-default-zone=drop
    firewall-cmd --permanent --zone=drop --add-service=ssh
    firewall-cmd --permanent --zone=drop --add-port="$HUB_PORT"/tcp
    firewall-cmd --reload
    info "firewalld: enabled — only SSH and port $HUB_PORT allowed inbound."
elif command -v iptables &>/dev/null; then
    iptables -F INPUT
    iptables -P INPUT DROP
    iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
    iptables -A INPUT -i lo -j ACCEPT
    iptables -A INPUT -p tcp --dport 22 -j ACCEPT
    iptables -A INPUT -p tcp --dport "$HUB_PORT" -j ACCEPT
    # Persist rules if iptables-save is available
    if command -v iptables-save &>/dev/null; then
        mkdir -p /etc/iptables
        iptables-save > /etc/iptables/rules.v4
    fi
    info "iptables: rules set — only SSH and port $HUB_PORT allowed inbound."
else
    warn "No supported firewall found (ufw/firewalld/iptables) — skipping firewall config."
    warn "Manually allow port $HUB_PORT and block all other inbound traffic."
fi

# ── Systemd service ───────────────────────────────────────────────
info "Installing systemd service..."
cat > "/etc/systemd/system/${SERVICE_NAME}.service" <<EOF
[Unit]
Description=Hub — Client-Sim Central Platform
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$HUB_USER
WorkingDirectory=$INSTALL_DIR
EnvironmentFile=$ENV_FILE
ExecStart=$INSTALL_DIR/start.sh
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=hub

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ReadWritePaths=$DATA_DIR $INSTALL_DIR

[Install]
WantedBy=multi-user.target
EOF

chmod +x "$INSTALL_DIR/start.sh"
chown -R "$HUB_USER:$HUB_USER" "$INSTALL_DIR"
systemctl daemon-reload
systemctl enable "$SERVICE_NAME"
systemctl restart "$SERVICE_NAME"

# ── Done ──────────────────────────────────────────────────────────
sleep 2
if systemctl is-active --quiet "$SERVICE_NAME"; then
    STATUS="${GREEN}running${NC}"
else
    STATUS="${RED}failed (check: journalctl -u $SERVICE_NAME)${NC}"
fi

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "  ✅ Hub installed! Service: $STATUS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  URL     : https://$(hostname -I | awk '{print $1}'):$HUB_PORT"
echo "  Admin   : admin / $ADMIN_PASSWORD"
echo "  Logs    : journalctl -u $SERVICE_NAME -f"
echo "  Data    : $DATA_DIR"
echo "  Env     : $ENV_FILE"
echo "  Firewall: port $HUB_PORT open, all other inbound blocked"
echo ""
echo "  ⚠  Self-signed TLS — browsers will warn."
echo "     To use your own cert, replace:"
echo "     $DATA_DIR/tls/cert.pem"
echo "     $DATA_DIR/tls/key.pem"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
